# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 02:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLCoureslist',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=9999, null=True, verbose_name='视频链接')),
                ('text', models.TextField(max_length=256, null=True, unique=True, verbose_name='课程标题')),
            ],
            options={
                'verbose_name': '全部课程视频',
                'verbose_name_plural': '全部课程视频',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Courese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courese_name', models.CharField(max_length=128, unique=True, verbose_name='课程名称')),
                ('num', models.IntegerField(null=True, verbose_name='课程节数')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='课程描述')),
                ('img', models.ImageField(default='avator/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='图片')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Category', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='观看用户')),
            ],
            options={
                'verbose_name': '课程大纲',
                'verbose_name_plural': '课程大纲',
            },
        ),
        migrations.AddField(
            model_name='allcoureslist',
            name='coure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Courese', verbose_name='所有课程'),
        ),
    ]
