# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonCoures',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('data', models.TextField(verbose_name='视频')),
                ('text', models.TextField(verbose_name='课程标题')),
            ],
            options={
                'verbose_name': 'python课程',
                'verbose_name_plural': 'python课程',
                'db_table': 'python_coures',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courese_name', models.CharField(max_length=128, unique=True, verbose_name='课程名称')),
                ('num', models.IntegerField(null=True, verbose_name='课程节数')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
