# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 11:56
from __future__ import unicode_literals

import apps.videos.vaild_difficulty
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courese',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='课程描述'),
        ),
        migrations.AddField(
            model_name='courese',
            name='level',
            field=models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, validators=[apps.videos.vaild_difficulty.valid_difficulty], verbose_name='课程等级'),
            preserve_default=False,
        ),
    ]
