# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-19 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_courese_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courese',
            options={'ordering': ['id'], 'verbose_name': '课程大纲', 'verbose_name_plural': '课程大纲'},
        ),
    ]
