# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_courese_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese',
            name='img',
            field=models.ImageField(default='avator/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='图片描述'),
        ),
    ]
