# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190919_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
