# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 14:40
from __future__ import unicode_literals

import apps.videos.vaild_difficulty
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190821_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='courese',
            name='tag',
            field=models.IntegerField(choices=[(1, 'python'), (2, 'java'), (3, 'Linux'), (4, 'C/C++'), (5, 'PHP'), (6, '大数据'), (7, 'go语言'), (8, 'web前端'), (9, 'Android'), (10, 'IOS'), (11, '网络信息')], default=1, validators=[apps.videos.vaild_difficulty.valid_difficulty1], verbose_name='标签'),
            preserve_default=False,
        ),
    ]
