# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20191003_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('tag', models.CharField(choices=[(1, 'python'), (2, 'java'), (3, 'Linux'), (4, 'C/C++'), (5, 'PHP'), (6, '大数据'), (7, 'go语言'), (8, 'web前端'), (9, 'Android'), (10, 'IOS'), (11, '网络信息')], max_length=20, verbose_name='标签名')),
            ],
        ),
        migrations.AlterField(
            model_name='courese',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Tag', verbose_name='标签'),
        ),
    ]
