# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 04:15
from __future__ import unicode_literals

import apps.videos.vaild_difficulty
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_courese_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese',
            name='level',
            field=models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], null=True, validators=[apps.videos.vaild_difficulty.valid_difficulty], verbose_name='课程等级'),
        ),
        migrations.AlterField(
            model_name='courese',
            name='tag',
            field=models.IntegerField(choices=[(1, 'python'), (2, 'java'), (3, 'Linux'), (4, 'C/C++'), (5, 'PHP'), (6, '大数据'), (7, 'go语言'), (8, 'web前端'), (9, 'Android'), (10, 'IOS'), (11, '网络信息')], null=True, validators=[apps.videos.vaild_difficulty.valid_difficulty1], verbose_name='标签'),
        ),
    ]
