# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200129_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoureslist',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courese',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
