# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20200130_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcoureslist',
            name='text',
        ),
        migrations.AddField(
            model_name='allcoureslist',
            name='title',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='课程标题'),
        ),
    ]
