# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 09:09
from __future__ import unicode_literals

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courese',
            name='level',
        ),
        migrations.AddField(
            model_name='courese',
            name='课程等级',
            field=models.IntegerField(null=True, verbose_name=apps.videos.models.Category),
        ),
    ]
