# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20200130_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoureslist',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='课程标题'),
        ),
    ]
