# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20190823_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courese',
            name='课程等级',
        ),
        migrations.AddField(
            model_name='courese',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Category', verbose_name='课程等级'),
        ),
    ]
