# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200130_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoureslist',
            name='coure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Courese', verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='allcoureslist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='视频编号'),
        ),
    ]
