# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20200131_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoureslist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='视频编号'),
        ),
        migrations.AlterField(
            model_name='allcoureslist',
            name='link',
            field=models.CharField(max_length=999999, null=True, unique=True, verbose_name='视频链接'),
        ),
        migrations.AlterField(
            model_name='courese',
            name='courese_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='课程名称'),
        ),
    ]
