# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0012_courese_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courese',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='观看用户'),
            preserve_default=False,
        ),
    ]
