# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-31 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20200131_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcoureslist',
            name='link',
            field=models.CharField(max_length=999999, null=True, verbose_name='视频链接'),
        ),
    ]
