# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-01 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0013_auto_20200131_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='courese',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='courese',
            name='create_time',
            field=models.DateTimeField(blank=True, default='2019-7-7', max_length=20),
        ),
        migrations.AddField(
            model_name='courese',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL, verbose_name='喜欢的视频'),
        ),
        migrations.AddField(
            model_name='courese',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
