# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-03 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20200203_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
    ]
