# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20200203_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese',
            name='create_time',
            field=models.DateTimeField(blank=True, default='2019-7-7', max_length=20, null=True),
        ),
    ]
