# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0017_auto_20200203_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcoureslist',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='like_video_id', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
    ]
