# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_allcoureslist_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcoureslist',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
