# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_remove_allcoureslist_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcoureslist',
            name='liked',
        ),
    ]
