# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avator_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=10, verbose_name='QQ号'),
        ),
    ]
