# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190819_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_sor',
            field=models.ImageField(default='avator/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像'),
        ),
    ]
